name: "build-n-test"
trigger:
  branches:
    include:
      - "feature/rewrite"
jobs:
  - job: "docker"
    strategy:
      parallel: 2
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - task: Docker@2
        inputs:
          command: build
          Dockerfile: cmds/grpc-backend/Dockerfile
          buildContext: "."
      - task: Docker@2
        inputs:
          command: build
          Dockerfile: cmds/http-gateway/Dockerfile
          buildContext: "."
  - job: "build_n_test"
    strategy:
      parallel: 1
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - task: GoTool@0
        inputs:
          version: '1.12'
      - bash: |
          set -exo pipefail
          export PATH=/usr/local/go/bin:$(go env GOPATH)/bin:${PATH}
          make && make test && make test-cockroach
        name: "build_and_test"
        displayName: "build_and_test"
        